### ISSUE TITLE
For TlruCache: on value expired, shouldn't the the item be evicted? i.e _internalStorage[key] = null; and return null?

### ISSUE THREAD

**Issue by mw66** [happy-san/dart-cacher#1]
Hi,

On value expired, shouldn't the the item be evicted? i.e _internalStorage[key] = null; and return null?

https://github.com/happy-san/dart-cacher/blob/trunk/lib/src/cache/cache.dart#L85

Why I didn't see this logic?

**Comment by happy-san** [comment]
Hey @mw66,
I think there are two scenarios here if a `_loaderFunc` is provided and the value has expired, we'll try to get the fresh value for the key. Otherwise, we should return null.

**Comment by mw66** [comment]
Yes, there should be a `return null` logic when the user did not provide `_loaderFunc`.

And I think most user will just use this container to `set` / `get` values (most common usage); while the `_loaderFunc` could be some complex external logic that people won't provide, and it should not be the responsibility of the container.

**Comment by happy-san** [comment]
`cacher 0.1.2` has this fix.

**Comment by mw66** [comment]
Thanks for the fix!
